sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
before_install:
    - npm install -g gulp
    - npm install -g bower
install:
    - npm install
    - bower install
script:
    - gulp
after_success:
    - docker build -t krack/ecuriesloup:test .

before_deploy:
    - cd dist && zip -ro ../ecuriesloup.zip * && cd ..
    - docker tag krack/ecuriesloup:test krack/ecuriesloup:${TRAVIS_TAG}
    - docker tag krack/ecuriesloup:${TRAVIS_TAG} krack/ecuriesloup:latest 
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push krack/ecuriesloup:${TRAVIS_TAG}
    - docker push krack/ecuriesloup:latest

deploy:
    provider: releases
    on:
        tags: true