version: '2'
services:
  load-balancer:
    ports:
    - ${HOST_PORT}
    image: rancher/lb-service-haproxy:v0.9.4
    labels:
      rap.host: ${EXPOSE_URL}
      rap.le_host: ${EXPOSE_URL}
      rap.port: ${HOST_PORT}
  web:
    labels:
      io.rancher.container.pull_image: always
    image: krack/ecuriesloup:${TAG}